### ISSUE TITLE
Splatfest bugs

### ISSUE THREAD

**Issue by BradleyDS2** [marcorei/splattim-fulfillment#29]
Hi, first of all, thanks for the wonderful work on this! I've been using it ever since you posted it on reddit months ago, it's so convenient and easy to use, my friend's and family use it as well.

There seems to be an issue though, when I ask "When's the next splatfest" it says "Mr Grizz is hiring for another" and gives the grizzco info 50% of the time. 

Also, if I ask "Splatfest" and say "North America" he says "Sad woomy, I've been splatted".

If I ask "When's the Splatfest" and say "North America" he gives the details on the upcoming splatfest.

With the grizzco info, I'm guessing that's due to a question regarding time being asked, which overlaps with the grizzco recognition. I'm not sure about the "Sad woomy, I've been splatted" though.

Sorry if this is the wrong repository to post the issue in, if I should post it in a different one instead please let me know.

**Comment by marcorei** [comment]
Hi @BradleyDS2 – thanks for reporting the issues!

`Sad woomy, I've been splatted` is due to the new Splatfests. The result data has a different structure then before. Will fix that soon 😅

I agree that the Splatfest / Grizzco issue could be fixed by optimizing the sample invocation phrases. I'll have to try different ones and go over the logs. 

Are you talking to Splat Tim via the Google Assistant or Amazon Alexa?

**Comment by marcorei** [comment]
Didn't mean to close this just yet...

**Comment by NaruZosa** [comment]
Thanks for the swift response!

I'm talking to Splat Tim via the Google Assistant.


The strange thing is if I asked "When's the Splatfest" then he gave details on it, but if I asked "Splatfest" then he says he's been splatted.

It looks like you may have fixed it already, and it's due to when you ask "Splatfest" without any context it thinks you're asking for the results of the previous Splatfest, which as you mentioned it couldn't parse due to a different structure.



Thanks again for your work on this, me and my friends use it on a near daily basis. It's so useful with a Google home since I don't need my phone unlocked or anything open, I can just ask a question and get an answer straight away so I know what the map rotation is or if grizzco is hiring, and if so with what weapons and map.

**Comment by marcorei** [comment]
I looked a bit more into the `When's the next Splatfest` vs `When's the next Salmon Run / GrizzCo` issue. That's a tricky one. Since `Splatfest` isn't a real word it is often misunderstood by Google. 

If you want to get involved more you could post here the next time it happens and include the date, time and timezone. Then I could look up what was understood instead of "Splatfest" and add it to the list.

**Comment by NaruZosa** [comment]
Ah, thought that might be the case.

It just did it then, literally less than a minute ago.

**Comment by marcorei** [comment]
Haha, it understood `when's the next black vest`.
I'll add `black vest`, `breakfast` and `splat first`, train the model again and do some tests. 

The app has to go through review again after that though. It might take a few days until the new version is live.

**Comment by NaruZosa** [comment]
Awesome, thanks again! Can't wait to ask Splat Tim what's for Breakfast!

**Comment by marcorei** [comment]
After a crazy long review time the new version is finally live!
